version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  igbinarybuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7igbinary
          build_service: centos7igbinary
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos7igbinaryrel
          build_service: centos7igbinaryrel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinary
          build_service: centos8igbinary
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos8igbinaryrel
          build_service: centos8igbinaryrel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7igbinaryphp73
          build_file: docker-compose.php73.yml
          build_service: centos7igbinaryphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinaryphp73
          build_file: docker-compose.php73.yml
          build_service: centos8igbinaryphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7igbinaryphp74
          build_file: docker-compose.php74.yml
          build_service: centos7igbinaryphp74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8igbinaryphp74
          build_file: docker-compose.php74.yml
          build_service: centos8igbinaryphp74
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7igbinaryphp7build
          compose_file: build/php71/docker-compose.yml
          build_service: centos7igbinaryphp7build
          requires:
            - centos7igbinary
      - docker-rpmbuild/image:
          name: centos7igbinaryphp7buildrel
          compose_file: build/php71/docker-compose.yml
          build_service: centos7igbinaryphp7buildrel
          requires:
            - centos7igbinaryrel
      - docker-rpmbuild/image:
          name: centos8igbinaryphp7build
          compose_file: build/php71/docker-compose.yml
          build_service: centos8igbinaryphp7build
          requires:
            - centos8igbinary
      - docker-rpmbuild/image:
          name: centos8igbinaryphp7buildrel
          compose_file: build/php71/docker-compose.yml
          build_service: centos8igbinaryphp7buildrel
          requires:
            - centos8igbinaryrel
      - docker-rpmbuild/image:
          name: centos7igbinaryphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos7igbinaryphp73build
          requires:
            - centos7igbinaryphp73
      - docker-rpmbuild/image:
          name: centos8igbinaryphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos8igbinaryphp73build
          requires:
            - centos8igbinaryphp73
      - docker-rpmbuild/image:
          name: centos7igbinaryphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos7igbinaryphp74build
          requires:
            - centos7igbinaryphp74
      - docker-rpmbuild/image:
          name: centos8igbinaryphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos8igbinaryphp74build
          requires:
            - centos8igbinaryphp74

